added surgeo into requirements.txt and completed surgeo backend in ap…
hcs-t4sg/t4sg-zest.ai pull request #21
Opened 2021-03-03 03:35 UTC by kaylanhua

…p.py, usage will be added in wiki section later, takes in surname/zipcode and returns a json

2021-03-03 07:08 UTC, chrisong88 commented on src/app.py
> +    # print for debugging
Could you please remove these debug statements? In general, when merging to 'dev', all temporary debugging code should be removed, to keep the main branch clean. 

Sidenote: comments are a little more nuanced. Feel free to keep in comments that you think are useful for informing the other engineers and explaining the code. But please take out all comments that are mostly for yourself (such as reminders).

2021-03-03 07:09 UTC, chrisong88 commented on src/app.py
> +    zip_series = pd.Series([zipcode])
This is really great, clean, descriptive, idiomatic code. It's super straightforward to read and you know when to break stuff up nicely! Great work!

2021-03-03 07:11 UTC, chrisong88 requested changes
Just some minor changes, removing some debug statements. Other than that, really nice job! Super clean code! Please make the changes (they should take <1 min) and then I'll submit the approval.

2021-03-04 04:36 UTC, chrisong88 approved these changes

2021-03-05 02:13 UTC, austinwl approved these changes

2021-03-05 02:14 UTC, merged